/* The following code was generated by JFlex 1.7.0 */

//lexico
/*1. paquete de importaciones*/
package Analizadores;
import java_cup.runtime.Symbol;
import Errores.Excepcion;
import java.util.ArrayList; //para errores
import Token.TokenInfo;



/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.7.0
 * from the specification file <tt>src/Analizadores/Scanner.jflex</tt>
 */
public class scanner implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = {
     0,  0,  0,  0,  0,  0,  0,  0,  0,  1, 11, 48, 48,  1,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     1,  9,  6,  0,  0,  0,  0,  0, 40, 41,  0,  0, 45, 46,  3,  0, 
     2,  2,  2,  2,  2,  2,  2,  2,  2,  2, 39, 38,  8, 44, 10,  0, 
    47, 16, 33, 21, 20, 18,  5, 15, 30, 26, 36,  5, 24, 17, 19, 14, 
    12,  5, 13, 23, 27, 28, 29,  5, 35, 37, 34, 31,  7, 32,  0,  4, 
     0, 16, 33, 21, 20, 18,  5, 15, 30, 26, 36,  5, 24, 17, 19, 14, 
    12,  5, 13, 23, 27, 28, 29,  5, 35, 37, 34, 43,  0, 42,  0,  0, 
     0,  0,  0,  0,  0, 48,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0
  };

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\1\1\5\2\1"+
    "\1\2\1\6\10\5\1\1\5\5\1\7\1\10\1\11"+
    "\1\12\1\13\1\14\1\15\1\16\1\17\1\20\1\1"+
    "\1\21\1\3\4\0\1\22\7\5\1\0\6\5\1\0"+
    "\3\5\1\0\2\5\1\0\2\5\1\0\1\5\1\23"+
    "\1\24\1\25\3\0\1\5\1\0\1\5\2\26\1\5"+
    "\1\27\1\30\1\31\1\5\2\32\1\33\1\34\3\5"+
    "\2\35\3\5\2\36\1\5\1\0\1\5\1\37\1\5"+
    "\1\0\1\5\2\0\1\2\1\5\1\0\2\5\1\40"+
    "\1\0\1\5\1\41\1\42\1\43\1\5\1\0\4\5"+
    "\1\0\1\5\1\0\2\5\1\0\1\5\1\0\1\5"+
    "\2\44\1\5\2\45\1\5\1\0\2\5\1\0\1\46"+
    "\1\0\1\5\1\0\2\5\1\0\1\5\1\2\4\5"+
    "\1\0\1\5\1\47\1\0\1\5\1\50\1\51\2\52"+
    "\1\0\1\5\2\53\1\0\1\5\1\54\1\0\1\5"+
    "\1\0\2\5\2\55\2\56\1\57\1\60\1\57\1\60"+
    "\1\0\1\5\1\0\1\5\2\61\1\0\1\5\1\62"+
    "\2\63\1\0\1\5\2\64\2\65";

  private static int [] zzUnpackAction() {
    int [] result = new int[203];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\61\0\142\0\223\0\304\0\365\0\u0126\0\u0157"+
    "\0\u0188\0\u01b9\0\61\0\u01ea\0\u021b\0\u024c\0\u027d\0\u02ae"+
    "\0\u02df\0\u0310\0\u0341\0\u0372\0\u03a3\0\u03d4\0\u0405\0\u0436"+
    "\0\u0467\0\61\0\61\0\61\0\u0498\0\61\0\61\0\61"+
    "\0\61\0\61\0\61\0\u04c9\0\61\0\304\0\365\0\u04fa"+
    "\0\u052b\0\u055c\0\61\0\u058d\0\u05be\0\u05ef\0\u0620\0\u0651"+
    "\0\u0682\0\u06b3\0\u06e4\0\u0715\0\u0746\0\u0777\0\u07a8\0\u07d9"+
    "\0\u080a\0\u083b\0\u086c\0\u089d\0\u08ce\0\u08ff\0\u0930\0\u0961"+
    "\0\u0992\0\u09c3\0\u09f4\0\u0a25\0\u0a56\0\61\0\61\0\u052b"+
    "\0\u0a87\0\u0ab8\0\u0ae9\0\u0b1a\0\u0b4b\0\u0b7c\0\61\0\u0126"+
    "\0\u0bad\0\u0126\0\u0bde\0\u0126\0\u0c0f\0\61\0\u0126\0\u0126"+
    "\0\u0126\0\u0c40\0\u0c71\0\u0ca2\0\61\0\u0126\0\u0cd3\0\u0d04"+
    "\0\u0d35\0\61\0\u0126\0\u0d66\0\u0d97\0\u0dc8\0\u0df9\0\u0e2a"+
    "\0\u0e5b\0\u0e8c\0\u0ebd\0\u0eee\0\61\0\u0f1f\0\u0f50\0\u0f81"+
    "\0\u0fb2\0\u0126\0\u0fe3\0\u1014\0\u0126\0\u0126\0\u0126\0\u1045"+
    "\0\u1076\0\u10a7\0\u10d8\0\u1109\0\u113a\0\u116b\0\u119c\0\u11cd"+
    "\0\u11fe\0\u122f\0\u1260\0\u1291\0\u12c2\0\u12f3\0\61\0\u0126"+
    "\0\u1324\0\u1355\0\u1386\0\u13b7\0\u13e8\0\u1419\0\u144a\0\u147b"+
    "\0\u0126\0\u14ac\0\u14dd\0\u150e\0\u153f\0\u1570\0\u15a1\0\u15d2"+
    "\0\u0eee\0\u1603\0\u1634\0\u1665\0\u1696\0\u16c7\0\u16f8\0\u0126"+
    "\0\u1729\0\u175a\0\u0126\0\61\0\u178b\0\u17bc\0\u17ed\0\u181e"+
    "\0\61\0\u0126\0\u184f\0\u1880\0\u0126\0\u18b1\0\u18e2\0\u1913"+
    "\0\u1944\0\u1975\0\61\0\u0126\0\61\0\u0126\0\61\0\61"+
    "\0\u0126\0\u0126\0\u19a6\0\u19d7\0\u1a08\0\u1a39\0\61\0\u0126"+
    "\0\u1a6a\0\u1a9b\0\u0126\0\61\0\u0126\0\u1acc\0\u1afd\0\61"+
    "\0\u0126\0\61\0\u0126";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[203];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\10\1\2"+
    "\1\11\1\12\1\2\1\13\1\14\1\15\1\7\1\16"+
    "\1\17\1\20\1\21\1\7\1\22\1\23\1\24\1\25"+
    "\1\26\1\2\1\7\1\27\1\7\1\30\1\31\1\32"+
    "\1\33\5\7\1\34\1\35\1\36\1\37\1\40\1\41"+
    "\1\42\1\43\1\44\1\45\63\0\1\3\61\0\1\4"+
    "\1\46\57\0\1\46\62\0\1\47\1\7\6\0\12\7"+
    "\1\0\2\7\1\0\5\7\2\0\5\7\15\0\1\7"+
    "\1\0\2\7\6\0\12\7\1\0\2\7\1\0\5\7"+
    "\2\0\5\7\13\0\6\50\1\51\52\50\11\0\1\52"+
    "\44\0\1\53\2\0\13\12\1\0\45\12\2\0\1\7"+
    "\1\0\2\7\6\0\1\7\1\54\10\7\1\0\2\7"+
    "\1\0\5\7\2\0\5\7\15\0\1\7\1\0\2\7"+
    "\6\0\6\7\1\55\3\7\1\0\2\7\1\0\5\7"+
    "\2\0\5\7\15\0\1\7\1\0\2\7\6\0\1\7"+
    "\1\56\10\7\1\0\2\7\1\0\5\7\2\0\5\7"+
    "\15\0\1\7\1\0\2\7\6\0\1\7\1\57\10\7"+
    "\1\0\2\7\1\0\5\7\2\0\5\7\15\0\1\7"+
    "\1\0\2\7\6\0\2\7\1\60\1\7\1\61\1\7"+
    "\1\62\3\7\1\0\2\7\1\63\1\64\1\7\1\65"+
    "\2\7\2\0\5\7\15\0\1\7\1\0\2\7\6\0"+
    "\7\7\1\66\2\7\1\0\2\7\1\0\5\7\2\0"+
    "\2\7\1\67\1\70\1\7\15\0\1\7\1\0\2\7"+
    "\6\0\2\7\1\71\7\7\1\0\2\7\1\72\1\73"+
    "\4\7\2\0\5\7\15\0\1\7\1\0\2\7\6\0"+
    "\2\7\1\74\7\7\1\0\2\7\1\0\4\7\1\75"+
    "\2\0\5\7\47\0\1\76\26\0\1\7\1\0\2\7"+
    "\6\0\12\7\1\0\2\7\1\0\2\7\1\77\2\7"+
    "\2\0\5\7\15\0\1\7\1\0\2\7\6\0\4\7"+
    "\1\100\5\7\1\0\2\7\1\0\5\7\2\0\5\7"+
    "\15\0\1\7\1\0\2\7\6\0\12\7\1\0\2\7"+
    "\1\101\1\102\4\7\2\0\5\7\15\0\1\7\1\0"+
    "\2\7\6\0\4\7\1\103\5\7\1\0\2\7\1\0"+
    "\5\7\2\0\5\7\15\0\1\7\1\0\2\7\6\0"+
    "\12\7\1\0\2\7\1\104\1\105\4\7\2\0\5\7"+
    "\62\0\1\106\23\0\1\107\46\0\6\50\1\110\52\50"+
    "\7\0\1\111\51\0\10\52\1\112\1\113\1\0\46\52"+
    "\2\0\1\7\1\0\2\7\6\0\2\7\1\114\7\7"+
    "\1\0\2\7\1\115\1\116\4\7\2\0\5\7\15\0"+
    "\1\7\1\0\2\7\6\0\12\7\1\117\1\120\1\7"+
    "\1\0\5\7\2\0\5\7\15\0\1\7\1\0\2\7"+
    "\6\0\4\7\1\121\5\7\1\0\2\7\1\0\5\7"+
    "\2\0\5\7\15\0\1\7\1\0\2\7\6\0\1\7"+
    "\1\122\10\7\1\0\2\7\1\0\5\7\2\0\5\7"+
    "\15\0\1\7\1\0\2\7\6\0\10\7\1\123\1\7"+
    "\1\0\2\7\1\0\5\7\2\0\5\7\15\0\1\7"+
    "\1\0\2\7\6\0\12\7\1\0\2\7\1\0\5\7"+
    "\2\0\2\7\1\124\2\7\15\0\1\7\1\0\2\7"+
    "\6\0\10\7\1\125\1\7\1\0\2\7\1\0\5\7"+
    "\2\0\5\7\36\0\1\126\37\0\1\7\1\0\2\7"+
    "\6\0\7\7\1\127\2\7\1\0\2\7\1\0\5\7"+
    "\2\0\5\7\15\0\1\7\1\0\2\7\6\0\12\7"+
    "\1\0\1\7\1\130\1\0\5\7\2\0\5\7\15\0"+
    "\1\7\1\0\2\7\6\0\10\7\1\131\1\7\1\0"+
    "\2\7\1\0\5\7\2\0\5\7\15\0\1\7\1\0"+
    "\2\7\6\0\6\7\1\132\3\7\1\0\2\7\1\0"+
    "\5\7\2\0\5\7\15\0\1\7\1\0\2\7\6\0"+
    "\6\7\1\133\3\7\1\0\2\7\1\0\5\7\2\0"+
    "\5\7\15\0\1\7\1\0\2\7\6\0\12\7\1\0"+
    "\2\7\1\0\2\7\1\134\2\7\2\0\5\7\50\0"+
    "\1\135\25\0\1\7\1\0\2\7\6\0\12\7\1\0"+
    "\2\7\1\0\3\7\1\136\1\7\2\0\5\7\15\0"+
    "\1\7\1\0\2\7\6\0\7\7\1\137\2\7\1\0"+
    "\1\7\1\140\1\0\5\7\2\0\5\7\15\0\1\7"+
    "\1\0\2\7\6\0\4\7\1\141\5\7\1\0\2\7"+
    "\1\0\5\7\2\0\5\7\34\0\1\142\41\0\1\7"+
    "\1\0\2\7\6\0\5\7\1\143\4\7\1\0\2\7"+
    "\1\0\5\7\2\0\5\7\15\0\1\7\1\0\2\7"+
    "\6\0\12\7\1\0\2\7\1\0\5\7\2\0\1\144"+
    "\4\7\46\0\1\145\27\0\1\7\1\0\2\7\6\0"+
    "\12\7\1\0\2\7\1\0\1\7\1\146\3\7\2\0"+
    "\5\7\15\0\1\7\1\0\2\7\6\0\1\7\1\147"+
    "\10\7\1\0\1\7\1\150\1\0\5\7\2\0\5\7"+
    "\41\0\2\151\33\0\1\7\1\0\2\7\6\0\12\7"+
    "\1\151\1\152\1\7\1\0\5\7\2\0\5\7\21\0"+
    "\1\153\52\0\10\112\1\154\1\112\1\154\46\112\10\52"+
    "\1\112\1\113\1\155\46\52\2\0\1\7\1\0\2\7"+
    "\6\0\3\7\1\156\6\7\1\0\2\7\1\0\5\7"+
    "\2\0\5\7\36\0\1\157\37\0\1\7\1\0\2\7"+
    "\6\0\7\7\1\160\2\7\1\0\2\7\1\0\5\7"+
    "\2\0\5\7\15\0\1\7\1\0\2\7\6\0\1\161"+
    "\11\7\1\0\2\7\1\0\5\7\2\0\5\7\15\0"+
    "\1\7\1\0\2\7\6\0\4\7\1\162\5\7\1\0"+
    "\2\7\1\0\5\7\2\0\5\7\15\0\1\7\1\0"+
    "\2\7\6\0\12\7\1\0\2\7\1\163\1\164\4\7"+
    "\2\0\5\7\15\0\1\7\1\0\2\7\6\0\11\7"+
    "\1\165\1\0\2\7\1\0\5\7\2\0\5\7\15\0"+
    "\1\7\1\0\2\7\6\0\12\7\1\0\2\7\1\0"+
    "\5\7\2\0\2\7\1\166\1\7\1\167\15\0\1\7"+
    "\1\0\2\7\6\0\12\7\1\0\2\7\1\0\5\7"+
    "\2\0\1\170\4\7\15\0\1\7\1\0\2\7\6\0"+
    "\12\7\1\171\1\172\1\7\1\0\5\7\2\0\5\7"+
    "\15\0\1\7\1\0\2\7\6\0\12\7\1\0\2\7"+
    "\1\0\2\7\1\173\2\7\2\0\5\7\15\0\1\7"+
    "\1\0\2\7\6\0\1\7\1\174\10\7\1\0\2\7"+
    "\1\0\5\7\2\0\5\7\15\0\1\7\1\0\2\7"+
    "\6\0\6\7\1\175\3\7\1\0\2\7\1\0\5\7"+
    "\2\0\5\7\47\0\1\176\26\0\1\7\1\0\2\7"+
    "\6\0\12\7\1\0\2\7\1\0\2\7\1\177\2\7"+
    "\2\0\5\7\15\0\1\7\1\0\2\7\6\0\12\7"+
    "\1\0\2\7\1\200\1\201\4\7\2\0\5\7\15\0"+
    "\1\7\1\0\2\7\6\0\12\7\1\0\2\7\1\0"+
    "\2\7\1\202\2\7\2\0\5\7\46\0\1\203\27\0"+
    "\1\7\1\0\2\7\6\0\12\7\1\0\2\7\1\0"+
    "\1\7\1\204\3\7\2\0\5\7\21\0\1\50\52\0"+
    "\11\154\1\205\47\154\2\0\1\7\1\0\2\7\6\0"+
    "\1\7\1\206\10\7\1\0\2\7\1\0\5\7\2\0"+
    "\5\7\46\0\1\207\27\0\1\7\1\0\2\7\6\0"+
    "\12\7\1\0\2\7\1\0\1\7\1\210\3\7\2\0"+
    "\5\7\15\0\1\7\1\0\2\7\6\0\12\7\1\0"+
    "\2\7\1\0\4\7\1\211\2\0\5\7\33\0\1\212"+
    "\42\0\1\7\1\0\2\7\6\0\4\7\1\213\5\7"+
    "\1\0\2\7\1\0\5\7\2\0\5\7\15\0\1\7"+
    "\1\0\2\7\6\0\12\7\1\0\1\7\1\214\1\0"+
    "\5\7\2\0\5\7\31\0\1\215\44\0\1\7\1\0"+
    "\2\7\6\0\2\7\1\216\7\7\1\0\2\7\1\0"+
    "\5\7\2\0\5\7\15\0\1\7\1\0\2\7\6\0"+
    "\5\7\1\217\4\7\1\0\2\7\1\0\5\7\2\0"+
    "\5\7\15\0\1\7\1\0\2\7\6\0\12\7\1\0"+
    "\2\7\1\0\5\7\1\220\1\0\5\7\15\0\1\7"+
    "\1\0\2\7\6\0\12\7\1\0\1\7\1\221\1\0"+
    "\5\7\2\0\5\7\43\0\1\222\32\0\1\7\1\0"+
    "\2\7\6\0\12\7\1\0\1\7\1\223\1\0\5\7"+
    "\2\0\5\7\33\0\1\224\42\0\1\7\1\0\2\7"+
    "\6\0\4\7\1\225\5\7\1\0\2\7\1\0\5\7"+
    "\2\0\5\7\15\0\1\7\1\0\2\7\6\0\6\7"+
    "\1\226\3\7\1\0\2\7\1\0\5\7\2\0\5\7"+
    "\31\0\1\227\44\0\1\7\1\0\2\7\6\0\2\7"+
    "\1\230\7\7\1\0\2\7\1\0\5\7\2\0\5\7"+
    "\13\0\11\154\1\205\1\231\46\154\2\0\1\7\1\0"+
    "\2\7\6\0\4\7\1\232\5\7\1\0\2\7\1\0"+
    "\5\7\2\0\5\7\15\0\1\7\1\0\2\7\6\0"+
    "\1\233\11\7\1\0\1\7\1\234\1\0\5\7\2\0"+
    "\1\235\4\7\36\0\1\236\37\0\1\7\1\0\2\7"+
    "\6\0\7\7\1\237\2\7\1\0\2\7\1\0\5\7"+
    "\2\0\5\7\15\0\1\7\1\0\2\7\6\0\6\7"+
    "\1\240\3\7\1\0\2\7\1\0\5\7\2\0\5\7"+
    "\43\0\1\241\32\0\1\7\1\0\2\7\6\0\12\7"+
    "\1\0\1\7\1\242\1\0\5\7\2\0\5\7\15\0"+
    "\1\7\1\0\2\7\6\0\7\7\1\243\2\7\1\0"+
    "\2\7\1\0\5\7\2\0\5\7\53\0\1\244\36\0"+
    "\1\245\44\0\1\7\1\0\2\7\6\0\2\7\1\246"+
    "\7\7\1\0\2\7\1\0\5\7\2\0\5\7\36\0"+
    "\1\247\37\0\1\7\1\0\2\7\6\0\7\7\1\250"+
    "\2\7\1\0\2\7\1\0\5\7\2\0\5\7\15\0"+
    "\1\7\1\0\2\7\6\0\12\7\1\251\1\252\1\7"+
    "\1\0\5\7\2\0\5\7\32\0\1\253\43\0\1\7"+
    "\1\0\2\7\6\0\3\7\1\254\6\7\1\0\2\7"+
    "\1\0\5\7\2\0\5\7\15\0\1\7\1\0\2\7"+
    "\6\0\5\7\1\255\4\7\1\0\2\7\1\0\5\7"+
    "\2\0\5\7\15\0\1\7\1\0\2\7\6\0\12\7"+
    "\1\0\2\7\1\256\1\257\4\7\2\0\5\7\15\0"+
    "\1\7\1\0\2\7\6\0\12\7\1\0\2\7\1\260"+
    "\1\261\4\7\2\0\5\7\15\0\1\7\1\0\2\7"+
    "\6\0\4\7\1\262\5\7\1\0\2\7\1\0\5\7"+
    "\2\0\5\7\33\0\1\263\42\0\1\7\1\0\2\7"+
    "\6\0\4\7\1\264\5\7\1\0\2\7\1\0\5\7"+
    "\2\0\5\7\35\0\1\265\40\0\1\7\1\0\2\7"+
    "\6\0\6\7\1\266\3\7\1\0\2\7\1\0\5\7"+
    "\2\0\5\7\56\0\1\267\1\0\1\270\15\0\1\7"+
    "\1\0\2\7\6\0\12\7\1\0\2\7\1\0\5\7"+
    "\2\0\2\7\1\271\1\7\1\272\55\0\1\273\20\0"+
    "\1\7\1\0\2\7\6\0\12\7\1\0\2\7\1\0"+
    "\5\7\2\0\1\7\1\274\3\7\30\0\1\275\45\0"+
    "\1\7\1\0\2\7\6\0\1\7\1\276\10\7\1\0"+
    "\2\7\1\0\5\7\2\0\5\7\35\0\1\277\40\0"+
    "\1\7\1\0\2\7\6\0\6\7\1\300\3\7\1\0"+
    "\2\7\1\0\5\7\2\0\5\7\36\0\1\301\37\0"+
    "\1\7\1\0\2\7\6\0\7\7\1\302\2\7\1\0"+
    "\2\7\1\0\5\7\2\0\5\7\15\0\1\7\1\0"+
    "\2\7\6\0\1\7\1\303\10\7\1\0\2\7\1\0"+
    "\5\7\2\0\5\7\33\0\1\304\42\0\1\7\1\0"+
    "\2\7\6\0\4\7\1\305\5\7\1\0\2\7\1\0"+
    "\5\7\2\0\5\7\33\0\1\306\42\0\1\7\1\0"+
    "\2\7\6\0\4\7\1\307\5\7\1\0\2\7\1\0"+
    "\5\7\2\0\5\7\35\0\1\310\40\0\1\7\1\0"+
    "\2\7\6\0\6\7\1\311\3\7\1\0\2\7\1\0"+
    "\5\7\2\0\5\7\34\0\1\312\41\0\1\7\1\0"+
    "\2\7\6\0\5\7\1\313\4\7\1\0\2\7\1\0"+
    "\5\7\2\0\5\7\13\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[6958];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\10\1\1\11\16\1\3\11\1\1\6\11"+
    "\1\1\1\11\1\1\4\0\1\11\7\1\1\0\6\1"+
    "\1\0\3\1\1\0\2\1\1\0\2\1\1\0\1\1"+
    "\2\11\1\1\3\0\1\1\1\0\1\1\1\11\6\1"+
    "\1\11\6\1\1\11\4\1\1\11\2\1\1\0\3\1"+
    "\1\0\1\1\2\0\1\11\1\1\1\0\3\1\1\0"+
    "\5\1\1\0\4\1\1\0\1\1\1\0\2\1\1\0"+
    "\1\1\1\0\1\1\1\11\5\1\1\0\2\1\1\0"+
    "\1\1\1\0\1\1\1\0\2\1\1\0\6\1\1\0"+
    "\2\1\1\0\2\1\1\11\2\1\1\0\1\1\1\11"+
    "\1\1\1\0\2\1\1\0\1\1\1\0\2\1\1\11"+
    "\1\1\1\11\1\1\2\11\2\1\1\0\1\1\1\0"+
    "\1\1\1\11\1\1\1\0\2\1\1\11\1\1\1\0"+
    "\1\1\1\11\1\1\1\11\1\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[203];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true iff the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true iff the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
    //codigo de usuario, clases , variables objetos, arreglos
    public ArrayList<Excepcion> Errores = new ArrayList();

    // Lista para almacenar los tokens
    private ArrayList<TokenInfo> tokens = new ArrayList<>();

    // Método para obtener la lista de tokens
    public ArrayList<TokenInfo> getTokens() {
        return tokens;
    }




  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public scanner(java.io.Reader in) {
      yyline = 1;
    yychar = 1;
    this.zzReader = in;
  }



  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { //guarda los errores lexicos
    Errores.add(new Excepcion("Lexico","Caracter no valido: "+ yytext(), yyline+"", yychar+""));
            } 
            // fall through
          case 54: break;
          case 2: 
            { 
            } 
            // fall through
          case 55: break;
          case 3: 
            { TokenInfo token = new TokenInfo(yytext(), "NUMERO", yyline, yychar); tokens.add(token);return new Symbol(sym.NUMERO,yyline,yychar,yytext());
            } 
            // fall through
          case 56: break;
          case 4: 
            { TokenInfo token = new TokenInfo(yytext(), "PUNTO", yyline, yychar);  tokens.add(token); return new Symbol(sym.PT,yyline,yychar, yytext());
            } 
            // fall through
          case 57: break;
          case 5: 
            { TokenInfo token = new TokenInfo(yytext(), "ID", yyline, yychar); tokens.add(token); return new Symbol(sym.ID,yyline,yychar,yytext());
            } 
            // fall through
          case 58: break;
          case 6: 
            { yychar=1;
            } 
            // fall through
          case 59: break;
          case 7: 
            { TokenInfo token = new TokenInfo(yytext(), "COR_IZQ", yyline, yychar);  tokens.add(token); return new Symbol(sym.COR_IZQ,yyline,yychar, yytext());
            } 
            // fall through
          case 60: break;
          case 8: 
            { TokenInfo token = new TokenInfo(yytext(), "COR_DER", yyline, yychar);  tokens.add(token); return new Symbol(sym.COR_DER,yyline,yychar, yytext());
            } 
            // fall through
          case 61: break;
          case 9: 
            { TokenInfo token = new TokenInfo(yytext(), "PT_COMA", yyline, yychar); tokens.add(token); return new Symbol(sym.PTCOMA,yyline,yychar, yytext());
            } 
            // fall through
          case 62: break;
          case 10: 
            { TokenInfo token = new TokenInfo(yytext(), "DOS_PT", yyline, yychar);  tokens.add(token); return new Symbol(sym.DOS_PT,yyline,yychar, yytext());
            } 
            // fall through
          case 63: break;
          case 11: 
            { TokenInfo token = new TokenInfo(yytext(), "PAR_IZQ", yyline, yychar);  tokens.add(token); return new Symbol(sym.PAR_IZQ,yyline,yychar, yytext());
            } 
            // fall through
          case 64: break;
          case 12: 
            { TokenInfo token = new TokenInfo(yytext(), "PAR_DER", yyline, yychar);  tokens.add(token); return new Symbol(sym.PAR_DER,yyline,yychar, yytext());
            } 
            // fall through
          case 65: break;
          case 13: 
            { TokenInfo token = new TokenInfo(yytext(), "LLAVE_DER", yyline, yychar);  tokens.add(token); return new Symbol(sym.LLAV_DER,yyline,yychar, yytext());
            } 
            // fall through
          case 66: break;
          case 14: 
            { TokenInfo token = new TokenInfo(yytext(), "LLAVE_IZQ", yyline, yychar);  tokens.add(token); return new Symbol(sym.LLAV_IZQ,yyline,yychar, yytext());
            } 
            // fall through
          case 67: break;
          case 15: 
            { TokenInfo token = new TokenInfo(yytext(), "ASIGNACION", yyline, yychar);  tokens.add(token); return new Symbol(sym.ASIGNACION,yyline,yychar, yytext());
            } 
            // fall through
          case 68: break;
          case 16: 
            { TokenInfo token = new TokenInfo(yytext(), "COMA", yyline, yychar);  tokens.add(token); return new Symbol(sym.COMA,yyline,yychar, yytext());
            } 
            // fall through
          case 69: break;
          case 17: 
            { TokenInfo token = new TokenInfo(yytext(), "ARROBA", yyline, yychar);  tokens.add(token); return new Symbol(sym.ARROBA,yyline,yychar,yytext());
            } 
            // fall through
          case 70: break;
          case 18: 
            { TokenInfo token = new TokenInfo(yytext(), "INICIALIZACION", yyline, yychar);  tokens.add(token); return new Symbol(sym.INICIALIZACION,yyline,yychar,yytext());
            } 
            // fall through
          case 71: break;
          case 19: 
            { TokenInfo token = new TokenInfo(yytext(), "ACCESO", yyline, yychar);  tokens.add(token); return new Symbol(sym.ACCESO,yyline,yychar, yytext());
            } 
            // fall through
          case 72: break;
          case 20: 
            { TokenInfo token = new TokenInfo(yytext(), "ASIGNA", yyline, yychar);  tokens.add(token); return new Symbol(sym.ASIGNA,yyline,yychar,yytext());
            } 
            // fall through
          case 73: break;
          case 21: 
            { TokenInfo token = new TokenInfo(yytext(), "CADENA", yyline, yychar); tokens.add(token); return new Symbol(sym.CADENA, yyline, yychar, yytext());
            } 
            // fall through
          case 74: break;
          case 22: 
            { TokenInfo token = new TokenInfo(yytext(), "RES", yyline, yychar);  tokens.add(token); return new Symbol(sym.RES,yyline,yychar,yytext());
            } 
            // fall through
          case 75: break;
          case 23: 
            { TokenInfo token = new TokenInfo(yytext(), "ARR", yyline, yychar);  tokens.add(token); return new Symbol(sym.ARR,yyline,yychar,yytext());
            } 
            // fall through
          case 76: break;
          case 24: 
            { TokenInfo token = new TokenInfo(yytext(), "MOD", yyline, yychar);  tokens.add(token); return new Symbol(sym.MOD,yyline,yychar,yytext());
            } 
            // fall through
          case 77: break;
          case 25: 
            { TokenInfo token = new TokenInfo(yytext(), "MAX", yyline, yychar);  tokens.add(token); return new Symbol(sym.MAX,yyline,yychar,yytext());
            } 
            // fall through
          case 78: break;
          case 26: 
            { TokenInfo token = new TokenInfo(yytext(), "MIN", yyline, yychar);  tokens.add(token); return new Symbol(sym.MIN,yyline,yychar,yytext());
            } 
            // fall through
          case 79: break;
          case 27: 
            { TokenInfo token = new TokenInfo(yytext(), "MUL", yyline, yychar);  tokens.add(token); return new Symbol(sym.MUL,yyline,yychar,yytext());
            } 
            // fall through
          case 80: break;
          case 28: 
            { TokenInfo token = new TokenInfo(yytext(), "END", yyline, yychar);  tokens.add(token); return new Symbol(sym.END,yyline,yychar,yytext());
            } 
            // fall through
          case 81: break;
          case 29: 
            { TokenInfo token = new TokenInfo(yytext(), "DIV", yyline, yychar);  tokens.add(token); return new Symbol(sym.DIV,yyline,yychar,yytext());
            } 
            // fall through
          case 82: break;
          case 30: 
            { TokenInfo token = new TokenInfo(yytext(), "SUM", yyline, yychar);  tokens.add(token); return new Symbol(sym.SUM,yyline,yychar,yytext());
            } 
            // fall through
          case 83: break;
          case 31: 
            { TokenInfo token = new TokenInfo(yytext(), "VAR", yyline, yychar);  tokens.add(token); return new Symbol(sym.VAR,yyline,yychar,yytext());
            } 
            // fall through
          case 84: break;
          case 32: 
            { TokenInfo token = new TokenInfo(yytext(), "MODA", yyline, yychar);  tokens.add(token); return new Symbol(sym.MODA,yyline,yychar,yytext());
            } 
            // fall through
          case 85: break;
          case 33: 
            { TokenInfo token = new TokenInfo(yytext(), "EXEC", yyline, yychar);  tokens.add(token); return new Symbol(sym.EXEC,yyline,yychar,yytext());
            } 
            // fall through
          case 86: break;
          case 34: 
            { TokenInfo token = new TokenInfo(yytext(), "X", yyline, yychar);  tokens.add(token); return new Symbol(sym.X,yyline,yychar,yytext());
            } 
            // fall through
          case 87: break;
          case 35: 
            { TokenInfo token = new TokenInfo(yytext(), "Y", yyline, yychar);  tokens.add(token); return new Symbol(sym.Y,yyline,yychar,yytext());
            } 
            // fall through
          case 88: break;
          case 36: 
            { TokenInfo token = new TokenInfo(yytext(), "PRINT", yyline, yychar);  tokens.add(token); return new Symbol(sym.PRINT,yyline,yychar,yytext());
            } 
            // fall through
          case 89: break;
          case 37: 
            { TokenInfo token = new TokenInfo(yytext(), "MEDIA", yyline, yychar);  tokens.add(token); return new Symbol(sym.MEDIA,yyline,yychar,yytext());
            } 
            // fall through
          case 90: break;
          case 38: 
            { TokenInfo token = new TokenInfo(yytext(), "LABEL", yyline, yychar);  tokens.add(token); return new Symbol(sym.LABEL,yyline,yychar,yytext());
            } 
            // fall through
          case 91: break;
          case 39: 
            { TokenInfo token = new TokenInfo(yytext(), "DOUBLE", yyline, yychar);  tokens.add(token); return new Symbol(sym.DOUBLE,yyline,yychar,yytext());
            } 
            // fall through
          case 92: break;
          case 40: 
            { TokenInfo token = new TokenInfo(yytext(), "COLUMN", yyline, yychar);  tokens.add(token); return new Symbol(sym.COLUMN,yyline,yychar,yytext());
            } 
            // fall through
          case 93: break;
          case 41: 
            { TokenInfo token = new TokenInfo(yytext(), "CHAR_ARRAY", yyline, yychar);  tokens.add(token); return new Symbol(sym.CHAR_ARRAY,yyline,yychar,yytext());
            } 
            // fall through
          case 94: break;
          case 42: 
            { TokenInfo token = new TokenInfo(yytext(), "TITULO", yyline, yychar);  tokens.add(token); return new Symbol(sym.TITULO,yyline,yychar,yytext());
            } 
            // fall through
          case 95: break;
          case 43: 
            { TokenInfo token = new TokenInfo(yytext(), "VALUES", yyline, yychar);  tokens.add(token); return new Symbol(sym.VALUES,yyline,yychar,yytext());
            } 
            // fall through
          case 96: break;
          case 44: 
            { TokenInfo token = new TokenInfo(yytext(), "PROGRAM", yyline, yychar);  tokens.add(token); return new Symbol(sym.PROGRAM,yyline,yychar,yytext());
            } 
            // fall through
          case 97: break;
          case 45: 
            { TokenInfo token = new TokenInfo(yytext(), "MEDIANA", yyline, yychar);  tokens.add(token); return new Symbol(sym.MEDIANA,yyline,yychar,yytext());
            } 
            // fall through
          case 98: break;
          case 46: 
            { TokenInfo token = new TokenInfo(yytext(), "CONSOLE", yyline, yychar);  tokens.add(token); return new Symbol(sym.CONSOLE,yyline,yychar,yytext());
            } 
            // fall through
          case 99: break;
          case 47: 
            { TokenInfo token = new TokenInfo(yytext(), "TITULOX", yyline, yychar);  tokens.add(token); return new Symbol(sym.TITULOX,yyline,yychar,yytext());
            } 
            // fall through
          case 100: break;
          case 48: 
            { TokenInfo token = new TokenInfo(yytext(), "TITULOY", yyline, yychar);  tokens.add(token); return new Symbol(sym.TITULOY,yyline,yychar,yytext());
            } 
            // fall through
          case 101: break;
          case 49: 
            { TokenInfo token = new TokenInfo(yytext(), "PIE", yyline, yychar);  tokens.add(token); return new Symbol(sym.PIE,yyline,yychar,yytext());
            } 
            // fall through
          case 102: break;
          case 50: 
            { TokenInfo token = new TokenInfo(yytext(), "BAR", yyline, yychar);  tokens.add(token); return new Symbol(sym.BAR,yyline,yychar,yytext());
            } 
            // fall through
          case 103: break;
          case 51: 
            { TokenInfo token = new TokenInfo(yytext(), "VARIANZA", yyline, yychar);  tokens.add(token); return new Symbol(sym.VARIANZA,yyline,yychar,yytext());
            } 
            // fall through
          case 104: break;
          case 52: 
            { TokenInfo token = new TokenInfo(yytext(), "LINE", yyline, yychar);  tokens.add(token); return new Symbol(sym.LINE,yyline,yychar,yytext());
            } 
            // fall through
          case 105: break;
          case 53: 
            { TokenInfo token = new TokenInfo(yytext(), "HISTOGRAM", yyline, yychar);  tokens.add(token); return new Symbol(sym.HISTOGRAM,yyline,yychar,yytext());
            } 
            // fall through
          case 106: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
