/* The following code was generated by JFlex 1.7.0 */

//lexico
/*1. paquete de importaciones*/
package Analizadores;
import java_cup.runtime.Symbol;
import Errores.Excepcion;
import java.util.ArrayList; //para errores
import Token.TokenInfo;



/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.7.0
 * from the specification file <tt>src/Analizadores/Scanner.jflex</tt>
 */
public class scanner implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = {
     0,  0,  0,  0,  0,  0,  0,  0,  0,  1, 11, 49, 49,  1,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     1,  9,  6,  0, 46,  0,  0,  0, 40, 41,  0,  0, 45, 47,  3,  0, 
     2,  2,  2,  2,  2,  2,  2,  2,  2,  2, 39, 38,  8, 44, 10,  0, 
    48, 16, 33, 21, 20, 18,  5, 15, 30, 26, 36,  5, 24, 17, 19, 14, 
    12,  5, 13, 23, 27, 28, 29,  5, 35, 37, 34, 31,  7, 32,  0,  4, 
     0, 16, 33, 21, 20, 18,  5, 15, 30, 26, 36,  5, 24, 17, 19, 14, 
    12,  5, 13, 23, 27, 28, 29,  5, 35, 37, 34, 43,  0, 42,  0,  0, 
     0,  0,  0,  0,  0, 49,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0
  };

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\1\1\5\2\1"+
    "\1\2\1\6\10\5\1\1\5\5\1\7\1\10\1\11"+
    "\1\12\1\13\1\14\1\15\1\16\1\17\1\20\1\21"+
    "\1\1\1\22\1\3\4\0\1\23\7\5\1\0\6\5"+
    "\1\0\3\5\1\0\2\5\1\0\2\5\1\0\1\5"+
    "\1\24\1\25\1\26\3\0\1\5\1\0\1\5\2\27"+
    "\1\5\1\30\1\31\1\32\1\5\2\33\1\34\1\35"+
    "\3\5\2\36\3\5\2\37\1\5\1\0\1\5\1\40"+
    "\1\5\1\0\1\5\2\0\1\2\1\5\1\0\2\5"+
    "\1\41\1\0\1\5\1\42\1\43\1\44\1\5\1\0"+
    "\4\5\1\0\1\5\1\0\2\5\1\0\1\5\1\0"+
    "\1\5\2\45\1\5\2\46\1\5\1\0\2\5\1\0"+
    "\1\47\1\0\1\5\1\0\2\5\1\0\1\5\1\2"+
    "\4\5\1\0\1\5\1\50\1\0\1\5\1\51\1\52"+
    "\2\53\1\0\1\5\2\54\1\0\1\5\1\55\1\0"+
    "\1\5\1\0\2\5\2\56\2\57\1\60\1\61\1\60"+
    "\1\61\1\0\1\5\1\0\1\5\2\62\1\0\1\5"+
    "\1\63\2\64\1\0\1\5\2\65\2\66";

  private static int [] zzUnpackAction() {
    int [] result = new int[204];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\62\0\144\0\226\0\310\0\372\0\u012c\0\u015e"+
    "\0\u0190\0\u01c2\0\62\0\u01f4\0\u0226\0\u0258\0\u028a\0\u02bc"+
    "\0\u02ee\0\u0320\0\u0352\0\u0384\0\u03b6\0\u03e8\0\u041a\0\u044c"+
    "\0\u047e\0\62\0\62\0\62\0\u04b0\0\62\0\62\0\62"+
    "\0\62\0\62\0\62\0\62\0\u04e2\0\62\0\310\0\372"+
    "\0\u0514\0\u0546\0\u0578\0\62\0\u05aa\0\u05dc\0\u060e\0\u0640"+
    "\0\u0672\0\u06a4\0\u06d6\0\u0708\0\u073a\0\u076c\0\u079e\0\u07d0"+
    "\0\u0802\0\u0834\0\u0866\0\u0898\0\u08ca\0\u08fc\0\u092e\0\u0960"+
    "\0\u0992\0\u09c4\0\u09f6\0\u0a28\0\u0a5a\0\u0a8c\0\62\0\62"+
    "\0\u0546\0\u0abe\0\u0af0\0\u0b22\0\u0b54\0\u0b86\0\u0bb8\0\62"+
    "\0\u012c\0\u0bea\0\u012c\0\u0c1c\0\u012c\0\u0c4e\0\62\0\u012c"+
    "\0\u012c\0\u012c\0\u0c80\0\u0cb2\0\u0ce4\0\62\0\u012c\0\u0d16"+
    "\0\u0d48\0\u0d7a\0\62\0\u012c\0\u0dac\0\u0dde\0\u0e10\0\u0e42"+
    "\0\u0e74\0\u0ea6\0\u0ed8\0\u0f0a\0\u0f3c\0\62\0\u0f6e\0\u0fa0"+
    "\0\u0fd2\0\u1004\0\u012c\0\u1036\0\u1068\0\u012c\0\u012c\0\u012c"+
    "\0\u109a\0\u10cc\0\u10fe\0\u1130\0\u1162\0\u1194\0\u11c6\0\u11f8"+
    "\0\u122a\0\u125c\0\u128e\0\u12c0\0\u12f2\0\u1324\0\u1356\0\62"+
    "\0\u012c\0\u1388\0\u13ba\0\u13ec\0\u141e\0\u1450\0\u1482\0\u14b4"+
    "\0\u14e6\0\u012c\0\u1518\0\u154a\0\u157c\0\u15ae\0\u15e0\0\u1612"+
    "\0\u1644\0\u0f3c\0\u1676\0\u16a8\0\u16da\0\u170c\0\u173e\0\u1770"+
    "\0\u012c\0\u17a2\0\u17d4\0\u012c\0\62\0\u1806\0\u1838\0\u186a"+
    "\0\u189c\0\62\0\u012c\0\u18ce\0\u1900\0\u012c\0\u1932\0\u1964"+
    "\0\u1996\0\u19c8\0\u19fa\0\62\0\u012c\0\62\0\u012c\0\62"+
    "\0\62\0\u012c\0\u012c\0\u1a2c\0\u1a5e\0\u1a90\0\u1ac2\0\62"+
    "\0\u012c\0\u1af4\0\u1b26\0\u012c\0\62\0\u012c\0\u1b58\0\u1b8a"+
    "\0\62\0\u012c\0\62\0\u012c";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[204];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\10\1\2"+
    "\1\11\1\12\1\2\1\13\1\14\1\15\1\7\1\16"+
    "\1\17\1\20\1\21\1\7\1\22\1\23\1\24\1\25"+
    "\1\26\1\2\1\7\1\27\1\7\1\30\1\31\1\32"+
    "\1\33\5\7\1\34\1\35\1\36\1\37\1\40\1\41"+
    "\1\42\1\43\1\44\1\45\1\46\64\0\1\3\62\0"+
    "\1\4\1\47\60\0\1\47\63\0\1\50\1\7\6\0"+
    "\12\7\1\0\2\7\1\0\5\7\2\0\5\7\16\0"+
    "\1\7\1\0\2\7\6\0\12\7\1\0\2\7\1\0"+
    "\5\7\2\0\5\7\14\0\6\51\1\52\53\51\11\0"+
    "\1\53\45\0\1\54\2\0\13\12\1\0\46\12\2\0"+
    "\1\7\1\0\2\7\6\0\1\7\1\55\10\7\1\0"+
    "\2\7\1\0\5\7\2\0\5\7\16\0\1\7\1\0"+
    "\2\7\6\0\6\7\1\56\3\7\1\0\2\7\1\0"+
    "\5\7\2\0\5\7\16\0\1\7\1\0\2\7\6\0"+
    "\1\7\1\57\10\7\1\0\2\7\1\0\5\7\2\0"+
    "\5\7\16\0\1\7\1\0\2\7\6\0\1\7\1\60"+
    "\10\7\1\0\2\7\1\0\5\7\2\0\5\7\16\0"+
    "\1\7\1\0\2\7\6\0\2\7\1\61\1\7\1\62"+
    "\1\7\1\63\3\7\1\0\2\7\1\64\1\65\1\7"+
    "\1\66\2\7\2\0\5\7\16\0\1\7\1\0\2\7"+
    "\6\0\7\7\1\67\2\7\1\0\2\7\1\0\5\7"+
    "\2\0\2\7\1\70\1\71\1\7\16\0\1\7\1\0"+
    "\2\7\6\0\2\7\1\72\7\7\1\0\2\7\1\73"+
    "\1\74\4\7\2\0\5\7\16\0\1\7\1\0\2\7"+
    "\6\0\2\7\1\75\7\7\1\0\2\7\1\0\4\7"+
    "\1\76\2\0\5\7\50\0\1\77\27\0\1\7\1\0"+
    "\2\7\6\0\12\7\1\0\2\7\1\0\2\7\1\100"+
    "\2\7\2\0\5\7\16\0\1\7\1\0\2\7\6\0"+
    "\4\7\1\101\5\7\1\0\2\7\1\0\5\7\2\0"+
    "\5\7\16\0\1\7\1\0\2\7\6\0\12\7\1\0"+
    "\2\7\1\102\1\103\4\7\2\0\5\7\16\0\1\7"+
    "\1\0\2\7\6\0\4\7\1\104\5\7\1\0\2\7"+
    "\1\0\5\7\2\0\5\7\16\0\1\7\1\0\2\7"+
    "\6\0\12\7\1\0\2\7\1\105\1\106\4\7\2\0"+
    "\5\7\63\0\1\107\24\0\1\110\47\0\6\51\1\111"+
    "\53\51\7\0\1\112\52\0\10\53\1\113\1\114\1\0"+
    "\47\53\2\0\1\7\1\0\2\7\6\0\2\7\1\115"+
    "\7\7\1\0\2\7\1\116\1\117\4\7\2\0\5\7"+
    "\16\0\1\7\1\0\2\7\6\0\12\7\1\120\1\121"+
    "\1\7\1\0\5\7\2\0\5\7\16\0\1\7\1\0"+
    "\2\7\6\0\4\7\1\122\5\7\1\0\2\7\1\0"+
    "\5\7\2\0\5\7\16\0\1\7\1\0\2\7\6\0"+
    "\1\7\1\123\10\7\1\0\2\7\1\0\5\7\2\0"+
    "\5\7\16\0\1\7\1\0\2\7\6\0\10\7\1\124"+
    "\1\7\1\0\2\7\1\0\5\7\2\0\5\7\16\0"+
    "\1\7\1\0\2\7\6\0\12\7\1\0\2\7\1\0"+
    "\5\7\2\0\2\7\1\125\2\7\16\0\1\7\1\0"+
    "\2\7\6\0\10\7\1\126\1\7\1\0\2\7\1\0"+
    "\5\7\2\0\5\7\37\0\1\127\40\0\1\7\1\0"+
    "\2\7\6\0\7\7\1\130\2\7\1\0\2\7\1\0"+
    "\5\7\2\0\5\7\16\0\1\7\1\0\2\7\6\0"+
    "\12\7\1\0\1\7\1\131\1\0\5\7\2\0\5\7"+
    "\16\0\1\7\1\0\2\7\6\0\10\7\1\132\1\7"+
    "\1\0\2\7\1\0\5\7\2\0\5\7\16\0\1\7"+
    "\1\0\2\7\6\0\6\7\1\133\3\7\1\0\2\7"+
    "\1\0\5\7\2\0\5\7\16\0\1\7\1\0\2\7"+
    "\6\0\6\7\1\134\3\7\1\0\2\7\1\0\5\7"+
    "\2\0\5\7\16\0\1\7\1\0\2\7\6\0\12\7"+
    "\1\0\2\7\1\0\2\7\1\135\2\7\2\0\5\7"+
    "\51\0\1\136\26\0\1\7\1\0\2\7\6\0\12\7"+
    "\1\0\2\7\1\0\3\7\1\137\1\7\2\0\5\7"+
    "\16\0\1\7\1\0\2\7\6\0\7\7\1\140\2\7"+
    "\1\0\1\7\1\141\1\0\5\7\2\0\5\7\16\0"+
    "\1\7\1\0\2\7\6\0\4\7\1\142\5\7\1\0"+
    "\2\7\1\0\5\7\2\0\5\7\35\0\1\143\42\0"+
    "\1\7\1\0\2\7\6\0\5\7\1\144\4\7\1\0"+
    "\2\7\1\0\5\7\2\0\5\7\16\0\1\7\1\0"+
    "\2\7\6\0\12\7\1\0\2\7\1\0\5\7\2\0"+
    "\1\145\4\7\47\0\1\146\30\0\1\7\1\0\2\7"+
    "\6\0\12\7\1\0\2\7\1\0\1\7\1\147\3\7"+
    "\2\0\5\7\16\0\1\7\1\0\2\7\6\0\1\7"+
    "\1\150\10\7\1\0\1\7\1\151\1\0\5\7\2\0"+
    "\5\7\42\0\2\152\34\0\1\7\1\0\2\7\6\0"+
    "\12\7\1\152\1\153\1\7\1\0\5\7\2\0\5\7"+
    "\22\0\1\154\53\0\10\113\1\155\1\113\1\155\47\113"+
    "\10\53\1\113\1\114\1\156\47\53\2\0\1\7\1\0"+
    "\2\7\6\0\3\7\1\157\6\7\1\0\2\7\1\0"+
    "\5\7\2\0\5\7\37\0\1\160\40\0\1\7\1\0"+
    "\2\7\6\0\7\7\1\161\2\7\1\0\2\7\1\0"+
    "\5\7\2\0\5\7\16\0\1\7\1\0\2\7\6\0"+
    "\1\162\11\7\1\0\2\7\1\0\5\7\2\0\5\7"+
    "\16\0\1\7\1\0\2\7\6\0\4\7\1\163\5\7"+
    "\1\0\2\7\1\0\5\7\2\0\5\7\16\0\1\7"+
    "\1\0\2\7\6\0\12\7\1\0\2\7\1\164\1\165"+
    "\4\7\2\0\5\7\16\0\1\7\1\0\2\7\6\0"+
    "\11\7\1\166\1\0\2\7\1\0\5\7\2\0\5\7"+
    "\16\0\1\7\1\0\2\7\6\0\12\7\1\0\2\7"+
    "\1\0\5\7\2\0\2\7\1\167\1\7\1\170\16\0"+
    "\1\7\1\0\2\7\6\0\12\7\1\0\2\7\1\0"+
    "\5\7\2\0\1\171\4\7\16\0\1\7\1\0\2\7"+
    "\6\0\12\7\1\172\1\173\1\7\1\0\5\7\2\0"+
    "\5\7\16\0\1\7\1\0\2\7\6\0\12\7\1\0"+
    "\2\7\1\0\2\7\1\174\2\7\2\0\5\7\16\0"+
    "\1\7\1\0\2\7\6\0\1\7\1\175\10\7\1\0"+
    "\2\7\1\0\5\7\2\0\5\7\16\0\1\7\1\0"+
    "\2\7\6\0\6\7\1\176\3\7\1\0\2\7\1\0"+
    "\5\7\2\0\5\7\50\0\1\177\27\0\1\7\1\0"+
    "\2\7\6\0\12\7\1\0\2\7\1\0\2\7\1\200"+
    "\2\7\2\0\5\7\16\0\1\7\1\0\2\7\6\0"+
    "\12\7\1\0\2\7\1\201\1\202\4\7\2\0\5\7"+
    "\16\0\1\7\1\0\2\7\6\0\12\7\1\0\2\7"+
    "\1\0\2\7\1\203\2\7\2\0\5\7\47\0\1\204"+
    "\30\0\1\7\1\0\2\7\6\0\12\7\1\0\2\7"+
    "\1\0\1\7\1\205\3\7\2\0\5\7\22\0\1\51"+
    "\53\0\11\155\1\206\50\155\2\0\1\7\1\0\2\7"+
    "\6\0\1\7\1\207\10\7\1\0\2\7\1\0\5\7"+
    "\2\0\5\7\47\0\1\210\30\0\1\7\1\0\2\7"+
    "\6\0\12\7\1\0\2\7\1\0\1\7\1\211\3\7"+
    "\2\0\5\7\16\0\1\7\1\0\2\7\6\0\12\7"+
    "\1\0\2\7\1\0\4\7\1\212\2\0\5\7\34\0"+
    "\1\213\43\0\1\7\1\0\2\7\6\0\4\7\1\214"+
    "\5\7\1\0\2\7\1\0\5\7\2\0\5\7\16\0"+
    "\1\7\1\0\2\7\6\0\12\7\1\0\1\7\1\215"+
    "\1\0\5\7\2\0\5\7\32\0\1\216\45\0\1\7"+
    "\1\0\2\7\6\0\2\7\1\217\7\7\1\0\2\7"+
    "\1\0\5\7\2\0\5\7\16\0\1\7\1\0\2\7"+
    "\6\0\5\7\1\220\4\7\1\0\2\7\1\0\5\7"+
    "\2\0\5\7\16\0\1\7\1\0\2\7\6\0\12\7"+
    "\1\0\2\7\1\0\5\7\1\221\1\0\5\7\16\0"+
    "\1\7\1\0\2\7\6\0\12\7\1\0\1\7\1\222"+
    "\1\0\5\7\2\0\5\7\44\0\1\223\33\0\1\7"+
    "\1\0\2\7\6\0\12\7\1\0\1\7\1\224\1\0"+
    "\5\7\2\0\5\7\34\0\1\225\43\0\1\7\1\0"+
    "\2\7\6\0\4\7\1\226\5\7\1\0\2\7\1\0"+
    "\5\7\2\0\5\7\16\0\1\7\1\0\2\7\6\0"+
    "\6\7\1\227\3\7\1\0\2\7\1\0\5\7\2\0"+
    "\5\7\32\0\1\230\45\0\1\7\1\0\2\7\6\0"+
    "\2\7\1\231\7\7\1\0\2\7\1\0\5\7\2\0"+
    "\5\7\14\0\11\155\1\206\1\232\47\155\2\0\1\7"+
    "\1\0\2\7\6\0\4\7\1\233\5\7\1\0\2\7"+
    "\1\0\5\7\2\0\5\7\16\0\1\7\1\0\2\7"+
    "\6\0\1\234\11\7\1\0\1\7\1\235\1\0\5\7"+
    "\2\0\1\236\4\7\37\0\1\237\40\0\1\7\1\0"+
    "\2\7\6\0\7\7\1\240\2\7\1\0\2\7\1\0"+
    "\5\7\2\0\5\7\16\0\1\7\1\0\2\7\6\0"+
    "\6\7\1\241\3\7\1\0\2\7\1\0\5\7\2\0"+
    "\5\7\44\0\1\242\33\0\1\7\1\0\2\7\6\0"+
    "\12\7\1\0\1\7\1\243\1\0\5\7\2\0\5\7"+
    "\16\0\1\7\1\0\2\7\6\0\7\7\1\244\2\7"+
    "\1\0\2\7\1\0\5\7\2\0\5\7\54\0\1\245"+
    "\37\0\1\246\45\0\1\7\1\0\2\7\6\0\2\7"+
    "\1\247\7\7\1\0\2\7\1\0\5\7\2\0\5\7"+
    "\37\0\1\250\40\0\1\7\1\0\2\7\6\0\7\7"+
    "\1\251\2\7\1\0\2\7\1\0\5\7\2\0\5\7"+
    "\16\0\1\7\1\0\2\7\6\0\12\7\1\252\1\253"+
    "\1\7\1\0\5\7\2\0\5\7\33\0\1\254\44\0"+
    "\1\7\1\0\2\7\6\0\3\7\1\255\6\7\1\0"+
    "\2\7\1\0\5\7\2\0\5\7\16\0\1\7\1\0"+
    "\2\7\6\0\5\7\1\256\4\7\1\0\2\7\1\0"+
    "\5\7\2\0\5\7\16\0\1\7\1\0\2\7\6\0"+
    "\12\7\1\0\2\7\1\257\1\260\4\7\2\0\5\7"+
    "\16\0\1\7\1\0\2\7\6\0\12\7\1\0\2\7"+
    "\1\261\1\262\4\7\2\0\5\7\16\0\1\7\1\0"+
    "\2\7\6\0\4\7\1\263\5\7\1\0\2\7\1\0"+
    "\5\7\2\0\5\7\34\0\1\264\43\0\1\7\1\0"+
    "\2\7\6\0\4\7\1\265\5\7\1\0\2\7\1\0"+
    "\5\7\2\0\5\7\36\0\1\266\41\0\1\7\1\0"+
    "\2\7\6\0\6\7\1\267\3\7\1\0\2\7\1\0"+
    "\5\7\2\0\5\7\57\0\1\270\1\0\1\271\16\0"+
    "\1\7\1\0\2\7\6\0\12\7\1\0\2\7\1\0"+
    "\5\7\2\0\2\7\1\272\1\7\1\273\56\0\1\274"+
    "\21\0\1\7\1\0\2\7\6\0\12\7\1\0\2\7"+
    "\1\0\5\7\2\0\1\7\1\275\3\7\31\0\1\276"+
    "\46\0\1\7\1\0\2\7\6\0\1\7\1\277\10\7"+
    "\1\0\2\7\1\0\5\7\2\0\5\7\36\0\1\300"+
    "\41\0\1\7\1\0\2\7\6\0\6\7\1\301\3\7"+
    "\1\0\2\7\1\0\5\7\2\0\5\7\37\0\1\302"+
    "\40\0\1\7\1\0\2\7\6\0\7\7\1\303\2\7"+
    "\1\0\2\7\1\0\5\7\2\0\5\7\16\0\1\7"+
    "\1\0\2\7\6\0\1\7\1\304\10\7\1\0\2\7"+
    "\1\0\5\7\2\0\5\7\34\0\1\305\43\0\1\7"+
    "\1\0\2\7\6\0\4\7\1\306\5\7\1\0\2\7"+
    "\1\0\5\7\2\0\5\7\34\0\1\307\43\0\1\7"+
    "\1\0\2\7\6\0\4\7\1\310\5\7\1\0\2\7"+
    "\1\0\5\7\2\0\5\7\36\0\1\311\41\0\1\7"+
    "\1\0\2\7\6\0\6\7\1\312\3\7\1\0\2\7"+
    "\1\0\5\7\2\0\5\7\35\0\1\313\42\0\1\7"+
    "\1\0\2\7\6\0\5\7\1\314\4\7\1\0\2\7"+
    "\1\0\5\7\2\0\5\7\14\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[7100];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\10\1\1\11\16\1\3\11\1\1\7\11"+
    "\1\1\1\11\1\1\4\0\1\11\7\1\1\0\6\1"+
    "\1\0\3\1\1\0\2\1\1\0\2\1\1\0\1\1"+
    "\2\11\1\1\3\0\1\1\1\0\1\1\1\11\6\1"+
    "\1\11\6\1\1\11\4\1\1\11\2\1\1\0\3\1"+
    "\1\0\1\1\2\0\1\11\1\1\1\0\3\1\1\0"+
    "\5\1\1\0\4\1\1\0\1\1\1\0\2\1\1\0"+
    "\1\1\1\0\1\1\1\11\5\1\1\0\2\1\1\0"+
    "\1\1\1\0\1\1\1\0\2\1\1\0\6\1\1\0"+
    "\2\1\1\0\2\1\1\11\2\1\1\0\1\1\1\11"+
    "\1\1\1\0\2\1\1\0\1\1\1\0\2\1\1\11"+
    "\1\1\1\11\1\1\2\11\2\1\1\0\1\1\1\0"+
    "\1\1\1\11\1\1\1\0\2\1\1\11\1\1\1\0"+
    "\1\1\1\11\1\1\1\11\1\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[204];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true iff the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true iff the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
    //codigo de usuario, clases , variables objetos, arreglos
    public ArrayList<Excepcion> Errores = new ArrayList();

    // Lista para almacenar los tokens
    private ArrayList<TokenInfo> tokens = new ArrayList<>();

    // Método para obtener la lista de tokens
    public ArrayList<TokenInfo> getTokens() {
        return tokens;
    }




  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public scanner(java.io.Reader in) {
      yyline = 1;
    yychar = 1;
    this.zzReader = in;
  }



  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { //guarda los errores lexicos
    System.out.println("Este es un error lexico: "+yytext()+ ", en la linea: "+yyline+", en la columna: "+yychar);
    Errores.add(new Excepcion("Lexico","Caracter no valido: "+ yytext(), yyline+"", yychar+""));
            } 
            // fall through
          case 55: break;
          case 2: 
            { 
            } 
            // fall through
          case 56: break;
          case 3: 
            { TokenInfo token = new TokenInfo(yytext(), "NUMERO", yyline, yychar); tokens.add(token);return new Symbol(sym.NUMERO,yyline,yychar,yytext());
            } 
            // fall through
          case 57: break;
          case 4: 
            { TokenInfo token = new TokenInfo(yytext(), "PUNTO", yyline, yychar);  tokens.add(token); return new Symbol(sym.PT,yyline,yychar, yytext());
            } 
            // fall through
          case 58: break;
          case 5: 
            { TokenInfo token = new TokenInfo(yytext(), "ID", yyline, yychar); tokens.add(token); return new Symbol(sym.ID,yyline,yychar,yytext());
            } 
            // fall through
          case 59: break;
          case 6: 
            { yychar=1;
            } 
            // fall through
          case 60: break;
          case 7: 
            { TokenInfo token = new TokenInfo(yytext(), "COR_IZQ", yyline, yychar);  tokens.add(token); return new Symbol(sym.COR_IZQ,yyline,yychar, yytext());
            } 
            // fall through
          case 61: break;
          case 8: 
            { TokenInfo token = new TokenInfo(yytext(), "COR_DER", yyline, yychar);  tokens.add(token); return new Symbol(sym.COR_DER,yyline,yychar, yytext());
            } 
            // fall through
          case 62: break;
          case 9: 
            { TokenInfo token = new TokenInfo(yytext(), "PT_COMA", yyline, yychar); tokens.add(token); return new Symbol(sym.PTCOMA,yyline,yychar, yytext());
            } 
            // fall through
          case 63: break;
          case 10: 
            { TokenInfo token = new TokenInfo(yytext(), "DOS_PT", yyline, yychar);  tokens.add(token); return new Symbol(sym.DOS_PT,yyline,yychar, yytext());
            } 
            // fall through
          case 64: break;
          case 11: 
            { TokenInfo token = new TokenInfo(yytext(), "PAR_IZQ", yyline, yychar);  tokens.add(token); return new Symbol(sym.PAR_IZQ,yyline,yychar, yytext());
            } 
            // fall through
          case 65: break;
          case 12: 
            { TokenInfo token = new TokenInfo(yytext(), "PAR_DER", yyline, yychar);  tokens.add(token); return new Symbol(sym.PAR_DER,yyline,yychar, yytext());
            } 
            // fall through
          case 66: break;
          case 13: 
            { TokenInfo token = new TokenInfo(yytext(), "LLAVE_DER", yyline, yychar);  tokens.add(token); return new Symbol(sym.LLAV_DER,yyline,yychar, yytext());
            } 
            // fall through
          case 67: break;
          case 14: 
            { TokenInfo token = new TokenInfo(yytext(), "LLAVE_IZQ", yyline, yychar);  tokens.add(token); return new Symbol(sym.LLAV_IZQ,yyline,yychar, yytext());
            } 
            // fall through
          case 68: break;
          case 15: 
            { TokenInfo token = new TokenInfo(yytext(), "ASIGNACION", yyline, yychar);  tokens.add(token); return new Symbol(sym.ASIGNACION,yyline,yychar, yytext());
            } 
            // fall through
          case 69: break;
          case 16: 
            { TokenInfo token = new TokenInfo(yytext(), "COMA", yyline, yychar);  tokens.add(token); return new Symbol(sym.COMA,yyline,yychar, yytext());
            } 
            // fall through
          case 70: break;
          case 17: 
            { TokenInfo token = new TokenInfo(yytext(), "S", yyline, yychar);  tokens.add(token); return new Symbol(sym.S,yyline,yychar,yytext());
            } 
            // fall through
          case 71: break;
          case 18: 
            { TokenInfo token = new TokenInfo(yytext(), "ARROBA", yyline, yychar);  tokens.add(token); return new Symbol(sym.ARROBA,yyline,yychar,yytext());
            } 
            // fall through
          case 72: break;
          case 19: 
            { TokenInfo token = new TokenInfo(yytext(), "INICIALIZACION", yyline, yychar);  tokens.add(token); return new Symbol(sym.INICIALIZACION,yyline,yychar,yytext());
            } 
            // fall through
          case 73: break;
          case 20: 
            { TokenInfo token = new TokenInfo(yytext(), "ACCESO", yyline, yychar);  tokens.add(token); return new Symbol(sym.ACCESO,yyline,yychar, yytext());
            } 
            // fall through
          case 74: break;
          case 21: 
            { TokenInfo token = new TokenInfo(yytext(), "ASIGNA", yyline, yychar);  tokens.add(token); return new Symbol(sym.ASIGNA,yyline,yychar,yytext());
            } 
            // fall through
          case 75: break;
          case 22: 
            { TokenInfo token = new TokenInfo(yytext(), "CADENA", yyline, yychar); tokens.add(token); return new Symbol(sym.CADENA, yyline, yychar, yytext());
            } 
            // fall through
          case 76: break;
          case 23: 
            { TokenInfo token = new TokenInfo(yytext(), "RES", yyline, yychar);  tokens.add(token); return new Symbol(sym.RES,yyline,yychar,yytext());
            } 
            // fall through
          case 77: break;
          case 24: 
            { TokenInfo token = new TokenInfo(yytext(), "ARR", yyline, yychar);  tokens.add(token); return new Symbol(sym.ARR,yyline,yychar,yytext());
            } 
            // fall through
          case 78: break;
          case 25: 
            { TokenInfo token = new TokenInfo(yytext(), "MOD", yyline, yychar);  tokens.add(token); return new Symbol(sym.MOD,yyline,yychar,yytext());
            } 
            // fall through
          case 79: break;
          case 26: 
            { TokenInfo token = new TokenInfo(yytext(), "MAX", yyline, yychar);  tokens.add(token); return new Symbol(sym.MAX,yyline,yychar,yytext());
            } 
            // fall through
          case 80: break;
          case 27: 
            { TokenInfo token = new TokenInfo(yytext(), "MIN", yyline, yychar);  tokens.add(token); return new Symbol(sym.MIN,yyline,yychar,yytext());
            } 
            // fall through
          case 81: break;
          case 28: 
            { TokenInfo token = new TokenInfo(yytext(), "MUL", yyline, yychar);  tokens.add(token); return new Symbol(sym.MUL,yyline,yychar,yytext());
            } 
            // fall through
          case 82: break;
          case 29: 
            { TokenInfo token = new TokenInfo(yytext(), "END", yyline, yychar);  tokens.add(token); return new Symbol(sym.END,yyline,yychar,yytext());
            } 
            // fall through
          case 83: break;
          case 30: 
            { TokenInfo token = new TokenInfo(yytext(), "DIV", yyline, yychar);  tokens.add(token); return new Symbol(sym.DIV,yyline,yychar,yytext());
            } 
            // fall through
          case 84: break;
          case 31: 
            { TokenInfo token = new TokenInfo(yytext(), "SUM", yyline, yychar);  tokens.add(token); return new Symbol(sym.SUM,yyline,yychar,yytext());
            } 
            // fall through
          case 85: break;
          case 32: 
            { TokenInfo token = new TokenInfo(yytext(), "VAR", yyline, yychar);  tokens.add(token); return new Symbol(sym.VAR,yyline,yychar,yytext());
            } 
            // fall through
          case 86: break;
          case 33: 
            { TokenInfo token = new TokenInfo(yytext(), "MODA", yyline, yychar);  tokens.add(token); return new Symbol(sym.MODA,yyline,yychar,yytext());
            } 
            // fall through
          case 87: break;
          case 34: 
            { TokenInfo token = new TokenInfo(yytext(), "EXEC", yyline, yychar);  tokens.add(token); return new Symbol(sym.EXEC,yyline,yychar,yytext());
            } 
            // fall through
          case 88: break;
          case 35: 
            { TokenInfo token = new TokenInfo(yytext(), "X", yyline, yychar);  tokens.add(token); return new Symbol(sym.X,yyline,yychar,yytext());
            } 
            // fall through
          case 89: break;
          case 36: 
            { TokenInfo token = new TokenInfo(yytext(), "Y", yyline, yychar);  tokens.add(token); return new Symbol(sym.Y,yyline,yychar,yytext());
            } 
            // fall through
          case 90: break;
          case 37: 
            { TokenInfo token = new TokenInfo(yytext(), "PRINT", yyline, yychar);  tokens.add(token); return new Symbol(sym.PRINT,yyline,yychar,yytext());
            } 
            // fall through
          case 91: break;
          case 38: 
            { TokenInfo token = new TokenInfo(yytext(), "MEDIA", yyline, yychar);  tokens.add(token); return new Symbol(sym.MEDIA,yyline,yychar,yytext());
            } 
            // fall through
          case 92: break;
          case 39: 
            { TokenInfo token = new TokenInfo(yytext(), "LABEL", yyline, yychar);  tokens.add(token); return new Symbol(sym.LABEL,yyline,yychar,yytext());
            } 
            // fall through
          case 93: break;
          case 40: 
            { TokenInfo token = new TokenInfo(yytext(), "DOUBLE", yyline, yychar);  tokens.add(token); return new Symbol(sym.DOUBLE,yyline,yychar,yytext());
            } 
            // fall through
          case 94: break;
          case 41: 
            { TokenInfo token = new TokenInfo(yytext(), "COLUMN", yyline, yychar);  tokens.add(token); return new Symbol(sym.COLUMN,yyline,yychar,yytext());
            } 
            // fall through
          case 95: break;
          case 42: 
            { TokenInfo token = new TokenInfo(yytext(), "CHAR_ARRAY", yyline, yychar);  tokens.add(token); return new Symbol(sym.CHAR_ARRAY,yyline,yychar,yytext());
            } 
            // fall through
          case 96: break;
          case 43: 
            { TokenInfo token = new TokenInfo(yytext(), "TITULO", yyline, yychar);  tokens.add(token); return new Symbol(sym.TITULO,yyline,yychar,yytext());
            } 
            // fall through
          case 97: break;
          case 44: 
            { TokenInfo token = new TokenInfo(yytext(), "VALUES", yyline, yychar);  tokens.add(token); return new Symbol(sym.VALUES,yyline,yychar,yytext());
            } 
            // fall through
          case 98: break;
          case 45: 
            { TokenInfo token = new TokenInfo(yytext(), "PROGRAM", yyline, yychar);  tokens.add(token); return new Symbol(sym.PROGRAM,yyline,yychar,yytext());
            } 
            // fall through
          case 99: break;
          case 46: 
            { TokenInfo token = new TokenInfo(yytext(), "MEDIANA", yyline, yychar);  tokens.add(token); return new Symbol(sym.MEDIANA,yyline,yychar,yytext());
            } 
            // fall through
          case 100: break;
          case 47: 
            { TokenInfo token = new TokenInfo(yytext(), "CONSOLE", yyline, yychar);  tokens.add(token); return new Symbol(sym.CONSOLE,yyline,yychar,yytext());
            } 
            // fall through
          case 101: break;
          case 48: 
            { TokenInfo token = new TokenInfo(yytext(), "TITULOX", yyline, yychar);  tokens.add(token); return new Symbol(sym.TITULOX,yyline,yychar,yytext());
            } 
            // fall through
          case 102: break;
          case 49: 
            { TokenInfo token = new TokenInfo(yytext(), "TITULOY", yyline, yychar);  tokens.add(token); return new Symbol(sym.TITULOY,yyline,yychar,yytext());
            } 
            // fall through
          case 103: break;
          case 50: 
            { TokenInfo token = new TokenInfo(yytext(), "PIE", yyline, yychar);  tokens.add(token); return new Symbol(sym.PIE,yyline,yychar,yytext());
            } 
            // fall through
          case 104: break;
          case 51: 
            { TokenInfo token = new TokenInfo(yytext(), "BAR", yyline, yychar);  tokens.add(token); return new Symbol(sym.BAR,yyline,yychar,yytext());
            } 
            // fall through
          case 105: break;
          case 52: 
            { TokenInfo token = new TokenInfo(yytext(), "VARIANZA", yyline, yychar);  tokens.add(token); return new Symbol(sym.VARIANZA,yyline,yychar,yytext());
            } 
            // fall through
          case 106: break;
          case 53: 
            { TokenInfo token = new TokenInfo(yytext(), "LINE", yyline, yychar);  tokens.add(token); return new Symbol(sym.LINE,yyline,yychar,yytext());
            } 
            // fall through
          case 107: break;
          case 54: 
            { TokenInfo token = new TokenInfo(yytext(), "HISTOGRAM", yyline, yychar);  tokens.add(token); return new Symbol(sym.HISTOGRAM,yyline,yychar,yytext());
            } 
            // fall through
          case 108: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
