
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MENOS = 14;
  public static final int CADENA = 23;
  public static final int S = 10;
  public static final int END = 20;
  public static final int CONSOLE = 21;
  public static final int ACCESO = 18;
  public static final int LLAV_IZQ = 5;
  public static final int ID = 24;
  public static final int POR = 15;
  public static final int PROGRAM = 19;
  public static final int LLAV_DER = 6;
  public static final int PT = 7;
  public static final int COMA = 9;
  public static final int ASIGNACION = 17;
  public static final int EOF = 0;
  public static final int DIV = 16;
  public static final int PAR_IZQ = 3;
  public static final int PRINT = 22;
  public static final int error = 1;
  public static final int PAR_DER = 4;
  public static final int COR_IZQ = 11;
  public static final int DOS_PT = 8;
  public static final int ENTERO = 25;
  public static final int COR_DER = 12;
  public static final int MAS = 13;
  public static final int DOUBLE = 26;
  public static final int PTCOMA = 2;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PTCOMA",
  "PAR_IZQ",
  "PAR_DER",
  "LLAV_IZQ",
  "LLAV_DER",
  "PT",
  "DOS_PT",
  "COMA",
  "S",
  "COR_IZQ",
  "COR_DER",
  "MAS",
  "MENOS",
  "POR",
  "DIV",
  "ASIGNACION",
  "ACCESO",
  "PROGRAM",
  "END",
  "CONSOLE",
  "PRINT",
  "CADENA",
  "ID",
  "ENTERO",
  "DOUBLE"
  };
}

