
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PT = 7;
  public static final int PAR_DER = 4;
  public static final int NUMERO = 29;
  public static final int DIVISON = 16;
  public static final int POR = 15;
  public static final int RES = 34;
  public static final int S = 10;
  public static final int CHAR_ARRAY = 31;
  public static final int DOUBLE = 28;
  public static final int COR_DER = 12;
  public static final int COLUMN = 44;
  public static final int ARROBA = 21;
  public static final int DIV = 36;
  public static final int ASIGNA = 19;
  public static final int MIN = 43;
  public static final int LLAV_IZQ = 5;
  public static final int ID = 27;
  public static final int MEDIANA = 39;
  public static final int EOF = 0;
  public static final int DOS_PT = 8;
  public static final int error = 1;
  public static final int PROGRAM = 22;
  public static final int MUL = 35;
  public static final int COMA = 9;
  public static final int CADENA = 26;
  public static final int MENOS = 14;
  public static final int MODA = 40;
  public static final int MOD = 37;
  public static final int PAR_IZQ = 3;
  public static final int INICIALIZACION = 20;
  public static final int ASIGNACION = 17;
  public static final int ACCESO = 18;
  public static final int COR_IZQ = 11;
  public static final int VARIANZA = 41;
  public static final int END = 23;
  public static final int SUM = 33;
  public static final int PTCOMA = 2;
  public static final int ARR = 32;
  public static final int MEDIA = 38;
  public static final int LLAV_DER = 6;
  public static final int MAX = 42;
  public static final int VAR = 30;
  public static final int PRINT = 25;
  public static final int CONSOLE = 24;
  public static final int MAS = 13;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PTCOMA",
  "PAR_IZQ",
  "PAR_DER",
  "LLAV_IZQ",
  "LLAV_DER",
  "PT",
  "DOS_PT",
  "COMA",
  "S",
  "COR_IZQ",
  "COR_DER",
  "MAS",
  "MENOS",
  "POR",
  "DIVISON",
  "ASIGNACION",
  "ACCESO",
  "ASIGNA",
  "INICIALIZACION",
  "ARROBA",
  "PROGRAM",
  "END",
  "CONSOLE",
  "PRINT",
  "CADENA",
  "ID",
  "DOUBLE",
  "NUMERO",
  "VAR",
  "CHAR_ARRAY",
  "ARR",
  "SUM",
  "RES",
  "MUL",
  "DIV",
  "MOD",
  "MEDIA",
  "MEDIANA",
  "MODA",
  "VARIANZA",
  "MAX",
  "MIN",
  "COLUMN"
  };
}

